frr version 8.4_git
frr defaults traditional
hostname CE3
log stdout
no ipv6 forwarding
!
interface eth1
 ip address 1.1.13.2/30
 ip ospf passive
exit
!
interface eth2
 ip address 1.1.34.1/30
exit
!
interface lo
 ip address 3.3.3.3/32
exit
!
router bgp 999
 bgp router-id 3.3.3.3
 neighbor 1.1.13.1 remote-as 100
 neighbor 4.4.4.4 remote-as 999
 neighbor 4.4.4.4 update-source lo
 !
 address-family ipv4 unicast
  network 3.3.3.3/32
 exit-address-family
exit
!
router ospf
 ospf router-id 3.3.3.3
 network 1.1.13.0/30 area 0
 network 1.1.34.0/30 area 0
 network 3.3.3.3/32 area 0
exit
!