frr version 8.4_git
frr defaults traditional
hostname CE3
log stdout
no ipv6 forwarding
!
interface eth1
 ip address 1.1.13.2/30
 ip ospf passive
exit
!
interface eth2
 ip address 1.1.34.1/30
exit
!
interface lo
 ip address 3.3.3.3/32
exit
!
router bgp 999
 bgp router-id 3.3.3.3
 neighbor 1.1.13.1 remote-as 100
 neighbor 1.1.13.1 route-map ALLOW-ALL in
 neighbor 1.1.13.1 route-map ALLOW-ALL out
 neighbor 4.4.4.4 remote-as 999
 neighbor 4.4.4.4 update-source lo
 neighbor 4.4.4.4 next-hop-self
 !
 address-family ipv4 unicast
  network 3.3.3.3/32
  network 1.1.13.0/30
 exit-address-family
exit
!
router ospf
 ospf router-id 3.3.3.3
 network 1.1.13.0/30 area 0
 network 1.1.34.0/30 area 0
 network 3.3.3.3/32 area 0
exit

 ip prefix-list PERMIT-ANY seq 5 permit 0.0.0.0/0 le 32

 route-map ALLOW-ALL permit 10
 match ip address prefix-list PERMIT-ANY
!